### ISSUE TITLE
SPC files can be played from RAR archives but not RSN archives

### ISSUE THREAD

**Issue by Salganos** [kode54/foo_gep#11]
Even when these are literally the exact same archive file, with the extension changed.

This wasn't an issue a few years ago, and I don't know what changed to break it, or if it is even an issue with this component.

**Comment by kode54** [comment]
As far as I can tell, there is an issue with my RSN support, but it still works. The problem is, when you add an .RSN file to the playlist, the .RSN file is also added first, followed by the contents.

**Comment by Salganos** [comment]
Hmm, that part doesn't seem to happen for me.  In testing that, however, it seems the problem may have had something to do with some invisible details of how the files were loaded in rather old playlists, as putting them back into a playlist anew (something which hadn't worked some months back) now solves the issue.

Admittedly, I should have tried that again today.  I will close the issue.
