### ISSUE TITLE
Game Emu Play plays 1943 NSF too fast

### ISSUE THREAD

**Issue by Mosesofmason** [kode54/foo_gep#13]
I download GEP and 1943 nsf, and play it in foobar, but get very fast playback, however other nsfs are in normal speed. 

GEP version 1.200 
foobar version 1.3.10
1943 NSF downloaded from: [here](http://atarihq.com/tsr/nsf/)

**Comment by kode54** [comment]
This NSF has a backwards speed value in its header: $1a41, which should be $411a. My player is probably one of the few that actually observes the speed fields. They are supposed to be little endian, not big endian as this file has.

I have corrected the file and uploaded the updated zip here:

https://f.losno.co/1943.zip

**Comment by Mosesofmason** [comment]
Thanks
